export const FETCH_TABLE_DATA = "FETCH_TABLE_DATA";
export const UPDATE_TABLE_DATA = "UPDATE_TABLE_DATA";
export const DELETE_TABLE_DATA = "DELETE_TABLE_DATA";
export const FILTER_TABLE_DATA = "FILTER_TABLE_DATA";